# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Build:
        strategy:
            matrix:
                platform: [ubuntu-latest, windows-latest]
                node-version: [22.x]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v4.1.6

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run prettier formatting
              run: npm run c

            - name: Test markdown files
              run: npm test
